name: SpigotExample
version: '${version}'
main: dev.queercoded.spigotexample.SpigotExample
api-version: 1.13
authors: [ queercoded, diademiemi ] # Change this to your username
description: Queer Coded example plugin, check the README!
commands:
  groundpound:
    description: Toggle the ground pound.
    usage: /groundpound
